// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdVqjBY_fSwGHZccGAcR8gfD0TNCs9PlI',
    appId: '1:495018971089:web:a4fedf63539e3e14ac5af0',
    messagingSenderId: '495018971089',
    projectId: 'dakauf-spec-generator',
    authDomain: 'dakauf-spec-generator.firebaseapp.com',
    storageBucket: 'dakauf-spec-generator.firebasestorage.app',
    measurementId: 'G-RTCNR2QL2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD363vL3exl87auuZJ91SP3k7XeF8wygoQ',
    appId: '1:495018971089:android:5664eca6caf5ac15ac5af0',
    messagingSenderId: '495018971089',
    projectId: 'dakauf-spec-generator',
    storageBucket: 'dakauf-spec-generator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jFvNkHWzChefCIPoUKTFJSb8VktFQlM',
    appId: '1:495018971089:ios:7615e449fb2b58edac5af0',
    messagingSenderId: '495018971089',
    projectId: 'dakauf-spec-generator',
    storageBucket: 'dakauf-spec-generator.firebasestorage.app',
    iosBundleId: 'com.example.dakaufSpecGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4jFvNkHWzChefCIPoUKTFJSb8VktFQlM',
    appId: '1:495018971089:ios:7615e449fb2b58edac5af0',
    messagingSenderId: '495018971089',
    projectId: 'dakauf-spec-generator',
    storageBucket: 'dakauf-spec-generator.firebasestorage.app',
    iosBundleId: 'com.example.dakaufSpecGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdVqjBY_fSwGHZccGAcR8gfD0TNCs9PlI',
    appId: '1:495018971089:web:0f4604d4dc905a0dac5af0',
    messagingSenderId: '495018971089',
    projectId: 'dakauf-spec-generator',
    authDomain: 'dakauf-spec-generator.firebaseapp.com',
    storageBucket: 'dakauf-spec-generator.firebasestorage.app',
    measurementId: 'G-53YGG8GN12',
  );
}
